# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e859aecfe46f658ba117884abedf78c8e9f724608a90c1c327a1d6676e10bbce1c5e0d28a7c336599be296726d42ccbc4d558fe7a9fd80c5474ecca7c5111d89

test:
  secret_key_base: 43421f5fb548b604179b58e05f57225d687e5e27cb3a017c08f7a4373b9de0f5b91353414070710616cfdeb8e1e011efd6dd2a36c6d1e14b1af2190865a3b52c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
